name: Format GO code

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  
  format:  
      name: format code
      runs-on: ubuntu-latest

      steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: test
        run: go test -v ./apis

      - name: format
        run: go fmt
