name: Check Svelte Project

on:
  push:
    branches:
      - main
  pull_request:

env:
  PUBLIC_AUTH0_DOMAIN: ''
  PUBLIC_AUTH0_ID: ''
  PRIVATE_AUTH0_SECRET: ''
  PRIVATE_DATEBASE_URL: ''
  PRIVATE_MAPS_API_KEY: ''
  PUBLIC_MAPS_API_KEY: ''

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check
