name: Check Svelte Project

on:
  push: 
    branches:
      - main
  pull_request:

jobs:
  check:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies  
      working-directory: ./website
      run: npm ci
    
    - name: Lint
      working-directory: ./website
      run: npm run lint

    - name: Check  
      working-directory: ./website
      run: npm run check
